// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_lvgl_waveshare7_squareline

#ifndef _TEST_LVGL_WAVESHARE7_SQUARELINE_UI_H
#define _TEST_LVGL_WAVESHARE7_SQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_ScreenLogo.h"
#include "ui_ScreenMenu.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_loading_1024x600_70_png);    // assets/LOGO_loading_1024x600_70.png
LV_IMG_DECLARE(ui_img_gddash_70_fond_png);    // assets/GDDash_70_Fond.png
LV_IMG_DECLARE(ui_img_icon04_png);    // assets/icon04.png
LV_IMG_DECLARE(ui_img_icon01_png);    // assets/icon01.png
LV_IMG_DECLARE(ui_img_icon02_png);    // assets/icon02.png
LV_IMG_DECLARE(ui_img_icon03_png);    // assets/icon03.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
