// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_lvgl_waveshare7_squareline

#include "ui.h"

lv_obj_t * ui_ScreenMenu = NULL;
lv_obj_t * ui_Display1 = NULL;
lv_obj_t * ui_Config2 = NULL;
lv_obj_t * ui_Leds3 = NULL;
lv_obj_t * ui_MiniMax4 = NULL;
lv_obj_t * ui_Display5 = NULL;
lv_obj_t * ui_Config6 = NULL;
lv_obj_t * ui_Leds7 = NULL;
lv_obj_t * ui_MiniMax8 = NULL;
lv_obj_t * ui_Dispaly9 = NULL;
// event funtions

// build funtions

void ui_ScreenMenu_screen_init(void)
{
    ui_ScreenMenu = lv_obj_create(NULL);
    lv_obj_add_flag(ui_ScreenMenu, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ScreenMenu, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_ScreenMenu, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_ScreenMenu, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_img_src(ui_ScreenMenu, &ui_img_gddash_70_fond_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display1 = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_Display1, 441);
    lv_obj_set_height(ui_Display1, 202);
    lv_obj_set_y(ui_Display1, 0);
    lv_obj_set_x(ui_Display1, lv_pct(-200));
    lv_obj_set_align(ui_Display1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Display1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Display1, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_Display1, lv_color_hex(0xF6FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Display1, &ui_img_icon04_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Config2 = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_Config2, 441);
    lv_obj_set_height(ui_Config2, 202);
    lv_obj_set_y(ui_Config2, 0);
    lv_obj_set_x(ui_Config2, lv_pct(-150));
    lv_obj_set_align(ui_Config2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Config2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Config2, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_Config2, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Config2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Config2, &ui_img_icon01_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Leds3 = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_Leds3, 441);
    lv_obj_set_height(ui_Leds3, 202);
    lv_obj_set_y(ui_Leds3, 0);
    lv_obj_set_x(ui_Leds3, lv_pct(-100));
    lv_obj_set_align(ui_Leds3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Leds3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Leds3, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_Leds3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Leds3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Leds3, &ui_img_icon02_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MiniMax4 = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_MiniMax4, 441);
    lv_obj_set_height(ui_MiniMax4, 202);
    lv_obj_set_y(ui_MiniMax4, 0);
    lv_obj_set_x(ui_MiniMax4, lv_pct(-50));
    lv_obj_set_align(ui_MiniMax4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MiniMax4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MiniMax4, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_MiniMax4, lv_color_hex(0xE300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MiniMax4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MiniMax4, &ui_img_icon03_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display5 = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_Display5, 441);
    lv_obj_set_height(ui_Display5, 202);
    lv_obj_set_align(ui_Display5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Display5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Display5, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_radius(ui_Display5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Display5, lv_color_hex(0xF6FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Display5, &ui_img_icon04_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Config6 = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_Config6, 441);
    lv_obj_set_height(ui_Config6, 202);
    lv_obj_set_y(ui_Config6, 0);
    lv_obj_set_x(ui_Config6, lv_pct(50));
    lv_obj_set_align(ui_Config6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Config6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Config6, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Config6, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_Config6, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Config6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Config6, &ui_img_icon01_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Leds7 = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_Leds7, 441);
    lv_obj_set_height(ui_Leds7, 202);
    lv_obj_set_y(ui_Leds7, 0);
    lv_obj_set_x(ui_Leds7, lv_pct(100));
    lv_obj_set_align(ui_Leds7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Leds7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Leds7, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_Leds7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Leds7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Leds7, &ui_img_icon02_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MiniMax8 = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_MiniMax8, 441);
    lv_obj_set_height(ui_MiniMax8, 202);
    lv_obj_set_y(ui_MiniMax8, 0);
    lv_obj_set_x(ui_MiniMax8, lv_pct(150));
    lv_obj_set_align(ui_MiniMax8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MiniMax8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MiniMax8, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scroll_dir(ui_MiniMax8, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_MiniMax8, lv_color_hex(0xE300FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MiniMax8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MiniMax8, &ui_img_icon03_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dispaly9 = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_Dispaly9, 441);
    lv_obj_set_height(ui_Dispaly9, 202);
    lv_obj_set_y(ui_Dispaly9, 0);
    lv_obj_set_x(ui_Dispaly9, lv_pct(200));
    lv_obj_set_align(ui_Dispaly9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dispaly9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Dispaly9, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_Dispaly9, lv_color_hex(0xF6FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dispaly9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Dispaly9, &ui_img_icon04_png, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenMenu_screen_destroy(void)
{
    if(ui_ScreenMenu) lv_obj_del(ui_ScreenMenu);

    // NULL screen variables
    ui_ScreenMenu = NULL;
    ui_Display1 = NULL;
    ui_Config2 = NULL;
    ui_Leds3 = NULL;
    ui_MiniMax4 = NULL;
    ui_Display5 = NULL;
    ui_Config6 = NULL;
    ui_Leds7 = NULL;
    ui_MiniMax8 = NULL;
    ui_Dispaly9 = NULL;

}
