// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_lvgl_waveshare7_squareline

#ifndef UI_SCREENMENU_H
#define UI_SCREENMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMenu
extern void ui_ScreenMenu_screen_init(void);
extern void ui_ScreenMenu_screen_destroy(void);
extern lv_obj_t * ui_ScreenMenu;
extern lv_obj_t * ui_Display1;
extern lv_obj_t * ui_Config2;
extern lv_obj_t * ui_Leds3;
extern lv_obj_t * ui_MiniMax4;
extern lv_obj_t * ui_Display5;
extern lv_obj_t * ui_Config6;
extern lv_obj_t * ui_Leds7;
extern lv_obj_t * ui_MiniMax8;
extern lv_obj_t * ui_Dispaly9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

