// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_lvgl_waveshare7_squareline

#include "ui.h"

lv_obj_t * ui_ScreenLogo = NULL;
// event funtions
void ui_event_ScreenLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 3000, &ui_ScreenMenu_screen_init);
    }
}

// build funtions

void ui_ScreenLogo_screen_init(void)
{
    ui_ScreenLogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLogo, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ScreenLogo, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_ScreenLogo, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_ScreenLogo, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_flex_flow(ui_ScreenLogo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ScreenLogo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(ui_ScreenLogo, &ui_img_logo_loading_1024x600_70_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenLogo, ui_event_ScreenLogo, LV_EVENT_ALL, NULL);

}

void ui_ScreenLogo_screen_destroy(void)
{
    if(ui_ScreenLogo) lv_obj_del(ui_ScreenLogo);

    // NULL screen variables
    ui_ScreenLogo = NULL;

}
